# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VisualsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.VisualsBox.setGeometry(QtCore.QRect(0, 180, 191, 191))
        self.VisualsBox.setObjectName("VisualsBox")
        self.widget = QtWidgets.QWidget(self.VisualsBox)
        self.widget.setGeometry(QtCore.QRect(10, 17, 171, 154))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scale_slider = QtWidgets.QLabel(self.widget)
        self.scale_slider.setObjectName("scale_slider")
        self.horizontalLayout_3.addWidget(self.scale_slider)
        self.scale_label = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_label.sizePolicy().hasHeightForWidth())
        self.scale_label.setSizePolicy(sizePolicy)
        self.scale_label.setOrientation(QtCore.Qt.Horizontal)
        self.scale_label.setObjectName("scale_label")
        self.horizontalLayout_3.addWidget(self.scale_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_slider = QtWidgets.QLabel(self.widget)
        self.start_slider.setObjectName("start_slider")
        self.horizontalLayout.addWidget(self.start_slider)
        self.start_label = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_label.sizePolicy().hasHeightForWidth())
        self.start_label.setSizePolicy(sizePolicy)
        self.start_label.setOrientation(QtCore.Qt.Horizontal)
        self.start_label.setObjectName("start_label")
        self.horizontalLayout.addWidget(self.start_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.end_slider = QtWidgets.QLabel(self.widget)
        self.end_slider.setObjectName("end_slider")
        self.horizontalLayout_2.addWidget(self.end_slider)
        self.end_label = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_label.sizePolicy().hasHeightForWidth())
        self.end_label.setSizePolicy(sizePolicy)
        self.end_label.setOrientation(QtCore.Qt.Horizontal)
        self.end_label.setObjectName("end_label")
        self.horizontalLayout_2.addWidget(self.end_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.flip_one_check = QtWidgets.QCheckBox(self.widget)
        self.flip_one_check.setObjectName("flip_one_check")
        self.verticalLayout.addWidget(self.flip_one_check)
        self.flip_two_check = QtWidgets.QCheckBox(self.widget)
        self.flip_two_check.setObjectName("flip_two_check")
        self.verticalLayout.addWidget(self.flip_two_check)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.font_size_slider = QtWidgets.QLabel(self.widget)
        self.font_size_slider.setObjectName("font_size_slider")
        self.horizontalLayout_4.addWidget(self.font_size_slider)
        self.font_size_label = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_size_label.sizePolicy().hasHeightForWidth())
        self.font_size_label.setSizePolicy(sizePolicy)
        self.font_size_label.setOrientation(QtCore.Qt.Horizontal)
        self.font_size_label.setObjectName("font_size_label")
        self.horizontalLayout_4.addWidget(self.font_size_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.font_y_slider = QtWidgets.QLabel(self.widget)
        self.font_y_slider.setObjectName("font_y_slider")
        self.horizontalLayout_5.addWidget(self.font_y_slider)
        self.font_y_label = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_y_label.sizePolicy().hasHeightForWidth())
        self.font_y_label.setSizePolicy(sizePolicy)
        self.font_y_label.setOrientation(QtCore.Qt.Horizontal)
        self.font_y_label.setObjectName("font_y_label")
        self.horizontalLayout_5.addWidget(self.font_y_label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.SettingsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SettingsBox.setGeometry(QtCore.QRect(-1, 40, 191, 111))
        self.SettingsBox.setObjectName("SettingsBox")
        self.widget1 = QtWidgets.QWidget(self.SettingsBox)
        self.widget1.setGeometry(QtCore.QRect(11, 21, 171, 75))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.show_gui_check = QtWidgets.QCheckBox(self.widget1)
        self.show_gui_check.setObjectName("show_gui_check")
        self.verticalLayout_2.addWidget(self.show_gui_check)
        self.full_screen_check = QtWidgets.QCheckBox(self.widget1)
        self.full_screen_check.setObjectName("full_screen_check")
        self.verticalLayout_2.addWidget(self.full_screen_check)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.select_screen_label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_screen_label.sizePolicy().hasHeightForWidth())
        self.select_screen_label.setSizePolicy(sizePolicy)
        self.select_screen_label.setObjectName("select_screen_label")
        self.horizontalLayout_12.addWidget(self.select_screen_label)
        self.select_screen_btn = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_screen_btn.sizePolicy().hasHeightForWidth())
        self.select_screen_btn.setSizePolicy(sizePolicy)
        self.select_screen_btn.setObjectName("select_screen_btn")
        self.horizontalLayout_12.addWidget(self.select_screen_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.InfoBox = QtWidgets.QGroupBox(self.centralwidget)
        self.InfoBox.setGeometry(QtCore.QRect(0, 370, 191, 151))
        self.InfoBox.setObjectName("InfoBox")
        self.widget2 = QtWidgets.QWidget(self.InfoBox)
        self.widget2.setGeometry(QtCore.QRect(11, 20, 171, 128))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scene_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_label.sizePolicy().hasHeightForWidth())
        self.scene_label.setSizePolicy(sizePolicy)
        self.scene_label.setObjectName("scene_label")
        self.horizontalLayout_6.addWidget(self.scene_label)
        self.scene_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_value.sizePolicy().hasHeightForWidth())
        self.scene_value.setSizePolicy(sizePolicy)
        self.scene_value.setObjectName("scene_value")
        self.horizontalLayout_6.addWidget(self.scene_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.position_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_label.sizePolicy().hasHeightForWidth())
        self.position_label.setSizePolicy(sizePolicy)
        self.position_label.setObjectName("position_label")
        self.horizontalLayout_7.addWidget(self.position_label)
        self.position_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_value.sizePolicy().hasHeightForWidth())
        self.position_value.setSizePolicy(sizePolicy)
        self.position_value.setObjectName("position_value")
        self.horizontalLayout_7.addWidget(self.position_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.correlation_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlation_label.sizePolicy().hasHeightForWidth())
        self.correlation_label.setSizePolicy(sizePolicy)
        self.correlation_label.setObjectName("correlation_label")
        self.horizontalLayout_8.addWidget(self.correlation_label)
        self.correlation_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlation_value.sizePolicy().hasHeightForWidth())
        self.correlation_value.setSizePolicy(sizePolicy)
        self.correlation_value.setObjectName("correlation_value")
        self.horizontalLayout_8.addWidget(self.correlation_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.score_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.score_label.sizePolicy().hasHeightForWidth())
        self.score_label.setSizePolicy(sizePolicy)
        self.score_label.setObjectName("score_label")
        self.horizontalLayout_9.addWidget(self.score_label)
        self.score_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.score_value.sizePolicy().hasHeightForWidth())
        self.score_value.setSizePolicy(sizePolicy)
        self.score_value.setObjectName("score_value")
        self.horizontalLayout_9.addWidget(self.score_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.power_one_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_one_label.sizePolicy().hasHeightForWidth())
        self.power_one_label.setSizePolicy(sizePolicy)
        self.power_one_label.setObjectName("power_one_label")
        self.horizontalLayout_10.addWidget(self.power_one_label)
        self.power_one_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_one_value.sizePolicy().hasHeightForWidth())
        self.power_one_value.setSizePolicy(sizePolicy)
        self.power_one_value.setObjectName("power_one_value")
        self.horizontalLayout_10.addWidget(self.power_one_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.power_two_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_two_label.sizePolicy().hasHeightForWidth())
        self.power_two_label.setSizePolicy(sizePolicy)
        self.power_two_label.setObjectName("power_two_label")
        self.horizontalLayout_11.addWidget(self.power_two_label)
        self.power_two_value = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_two_value.sizePolicy().hasHeightForWidth())
        self.power_two_value.setSizePolicy(sizePolicy)
        self.power_two_value.setObjectName("power_two_value")
        self.horizontalLayout_11.addWidget(self.power_two_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(190, 0, 791, 591))
        self.widget3.setObjectName("widget3")
        self.CentralView = QtWidgets.QHBoxLayout(self.widget3)
        self.CentralView.setContentsMargins(0, 0, 0, 0)
        self.CentralView.setObjectName("CentralView")
        self.head_one = QtWidgets.QGraphicsView(self.widget3)
        self.head_one.setObjectName("head_one")
        self.CentralView.addWidget(self.head_one)
        self.head_two = QtWidgets.QGraphicsView(self.widget3)
        self.head_two.setObjectName("head_two")
        self.CentralView.addWidget(self.head_two)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 22))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.VisualsBox.setTitle(_translate("MainWindow", "Visuals"))
        self.scale_slider.setText(_translate("MainWindow", "Scale"))
        self.start_slider.setText(_translate("MainWindow", "Start"))
        self.end_slider.setText(_translate("MainWindow", "End"))
        self.flip_one_check.setText(_translate("MainWindow", "Flip Head 1"))
        self.flip_two_check.setText(_translate("MainWindow", "Flip Head 2"))
        self.font_size_slider.setText(_translate("MainWindow", "FontSize"))
        self.font_y_slider.setText(_translate("MainWindow", "FontY"))
        self.SettingsBox.setTitle(_translate("MainWindow", "Settings"))
        self.show_gui_check.setText(_translate("MainWindow", "Show GUI (G)"))
        self.full_screen_check.setText(_translate("MainWindow", "Full Screen (F)"))
        self.select_screen_label.setText(_translate("MainWindow", "Select Screen"))
        self.select_screen_btn.setText(_translate("MainWindow", "1"))
        self.InfoBox.setTitle(_translate("MainWindow", "Info"))
        self.scene_label.setText(_translate("MainWindow", "Scene"))
        self.scene_value.setText(_translate("MainWindow", "0"))
        self.position_label.setText(_translate("MainWindow", "Position"))
        self.position_value.setText(_translate("MainWindow", "0"))
        self.correlation_label.setText(_translate("MainWindow", "Correlation"))
        self.correlation_value.setText(_translate("MainWindow", "0"))
        self.score_label.setText(_translate("MainWindow", "Score"))
        self.score_value.setText(_translate("MainWindow", "0"))
        self.power_one_label.setText(_translate("MainWindow", "Power 1"))
        self.power_one_value.setText(_translate("MainWindow", "0"))
        self.power_two_label.setText(_translate("MainWindow", "Power 2"))
        self.power_two_value.setText(_translate("MainWindow", "0"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
